version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ops/Dockerfile
    env_file:
      - ops/.env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: "redis"
    ports:
      - "6379:6379"
